# Generated by Django 4.1.5 on 2023-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.EmailField(default=None, max_length=254, verbose_name='Ник'),
        ),
    ]
