# Generated by Django 4.1.5 on 2023-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=220, verbose_name='username'),
        ),
    ]
